### ISSUE TITLE
plugin not working in CICD

### ISSUE THREAD

**Issue by TheGarkine** [twilio-infra-as-code/plugin-twilio-infra#30]
Tested in Jenkins, but you had some clean up going on a few months ago, banning the `--yes` flag. This causes major problems in CICD since I cannot deploy my stuff there now.

I will probably fix this pretty soon, but you should be informed!

**Comment by vernig** [comment]
Hey @TheGarkine you are absolutely right. When we refactor the code for the CLI we simplified the wrapper to the pulumi CLI and we didn't bring in all the flags. 

Happy to get a PR for that if you have time to work on. Otherwise I can look into that.

**Comment by TheGarkine** [comment]
Hey @vernig, will work on that today or tomorrow and send you a PR!

**Comment by TheGarkine** [comment]
Hey, @vernig , #31 gives an option to fix it. This would **not** allow older users to simple upgrade without the need to add the `--yes` option to their pipelines. I think that would be the best way though.
